In [1]:
# import pandas library

import pandas as pd

In [2]:
# read in relevant files

df_score = pd.read_csv("score_analysis_new.csv")
df_score = df_score.drop(columns = "Unnamed: 0")

In [3]:
df_score.head()

,LSOA_Code,LSOA_Name,LADcode,Local_authority_name,pop_2001,pop_2011,Median_House_Prices_2001,Median_House_Prices_2011,All_cat_qual_2001,Level_4_qualifications_and_above_2001,...,Median_income_2001,Median_income_2011,Score_2001,Score_2011,Rank_2001,Rank_2011,Rank_chg,Z_score,score_chg,status
0,E01000001,CityofLondon001A,E09000001,City of London,1600,1465,245424,497000,1423,1029,...,45630,65520,2.192576,4.439991,65.0,147.0,-82.0,-0.182004,2.247415,STB
1,E01000002,CityofLondon001B,E09000001,City of London,1470,1436,235000,528750,1261,862,...,44970,66300,1.993602,4.647998,89.0,128.0,-39.0,-0.086563,2.654396,STB
2,E01000003,CityofLondon001C,E09000001,City of London,1537,1346,190000,335000,1230,619,...,36330,54140,0.517826,2.163691,613.0,712.0,-99.0,-0.219737,1.645864,STB
3,E01000005,CityofLondon001E,E09000001,City of London,1073,985,137500,300000,763,239,...,31530,46740,-0.648125,0.806908,1843.0,1730.0,113.0,0.250811,1.455033,STB
4,E01000006,BarkingandDagenham016A,E09000002,Barking and Dagenham,1571,1703,60000,232500,1160,261,...,26360,38200,-1.529709,0.006023,3841.0,2827.0,1014.0,2.250639,1.535732,ASC

In [4]:
# verify the breakdown of neighbourhood states

df_score.groupby("status").size()

status
ASC     732
DEC     619
STB    3484
dtype: int64

In [5]:
# extract only ascending LSOAs

ascending_LSOA = df_score[df_score["status"] == "ASC"]

In [6]:
# check extracted dataframe

ascending_LSOA

,LSOA_Code,LSOA_Name,LADcode,Local_authority_name,pop_2001,pop_2011,Median_House_Prices_2001,Median_House_Prices_2011,All_cat_qual_2001,Level_4_qualifications_and_above_2001,...,Median_income_2001,Median_income_2011,Score_2001,Score_2011,Rank_2001,Rank_2011,Rank_chg,Z_score,score_chg,status
4,E01000006,BarkingandDagenham016A,E09000002,Barking and Dagenham,1571,1703,60000,232500,1160,261,...,26360,38200,-1.529709,0.006023,3841.0,2827.0,1014.0,2.250639,1.535732,ASC
8,E01000010,BarkingandDagenham015C,E09000002,Barking and Dagenham,1442,2840,90000,143000,1018,218,...,22740,35190,-1.607967,-0.213208,4026.0,3219.0,807.0,1.791189,1.394760,ASC
26,E01000029,BarkingandDagenham001C,E09000002,Barking and Dagenham,1624,1602,107500,244500,1119,141,...,26080,35540,-1.546211,-0.316585,3887.0,3426.0,461.0,1.023220,1.229626,ASC
29,E01000032,BarkingandDagenham002B,E09000002,Barking and Dagenham,1561,1629,100500,234000,1120,127,...,25590,36230,-1.645111,-0.331296,4127.0,3455.0,672.0,1.491548,1.313815,ASC
40,E01000043,BarkingandDagenham019B,E09000002,Barking and Dagenham,1245,1358,85995,217500,896,98,...,23990,34390,-1.787100,-0.583596,4439.0,3976.0,463.0,1.027659,1.203505,ASC
65,E01000069,BarkingandDagenham011C,E09000002,Barking and Dagenham,1412,1763,135498,286250,1002,94,...,31130,42310,-1.180167,0.264022,2936.0,2425.0,511.0,1.134198,1.444189,ASC
88,E01000092,BarkingandDagenham019E,E09000002,Barking and Dagenham,1432,2674,84500,180000,1002,118,...,23510,34850,-1.796589,-0.591428,4454.0,3993.0,461.0,1.023220,1.205161,ASC
113,E01000117,Barnet010A,E09000003,Barnet,1536,1819,175000,335000,1115,227,...,26860,37810,-0.956993,0.626711,2397.0,1919.0,478.0,1.060952,1.583704,ASC
126,E01000130,Barnet021A,E09000003,Barnet,1540,1603,66978,233000,1112,238,...,21850,31010,-1.702370,-0.467632,4261.0,3750.0,511.0,1.134198,1.234738,ASC
132,E01000136,Barnet038B,E09000003,Barnet,1442,1532,287475,2825000,1001,574,...,37470,59440,1.206059,14.456525,257.0,1.0,256.0,0.568209,13.250466,ASC
133,E01000137,Barnet041A,E09000003,Barnet,1511,1729,115000,312000,1040,295,...,24770,32720,-1.149848,0.278280,2862.0,2400.0,462.0,1.025439,1.428128,ASC
135,E01000139,Barnet041B,E09000003,Barnet,1350,1429,182500,900000,1008,464,...,29470,39690,0.027218,3.841467,987.0,224.0,763.0,1.693528,3.814249,ASC
139,E01000143,Barnet041D,E09000003,Barnet,1359,1459,135000,1450000,1056,258,...,23890,33110,-1.248563,5.591105,3090.0,86.0,3004.0,6.667575,6.839668,ASC
142,E01000146,Barnet038D,E09000003,Barnet,1472,1716,309750,834938,1135,651,...,31500,41460,0.951966,3.737328,379.0,244.0,135.0,0.299641,2.785362,ASC
154,E01000159,Barnet015B,E09000003,Barnet,1491,1777,133000,427750,1117,330,...,27630,39500,-0.848395,1.259143,2185.0,1300.0,885.0,1.964315,2.107539,ASC
159,E01000164,Barnet022D,E09000003,Barnet,1500,1686,95000,292250,1137,291,...,24280,33790,-1.304799,0.156619,3250.0,2576.0,674.0,1.495987,1.461417,ASC
164,E01000169,Barnet003C,E09000003,Barnet,1493,1490,106000,307750,1158,378,...,28100,39600,-0.834360,0.843612,2160.0,1692.0,468.0,1.038757,1.677972,ASC
171,E01000176,Barnet027A,E09000003,Barnet,1519,1613,95000,382500,1037,289,...,24920,34160,-1.329576,0.570950,3316.0,1978.0,1338.0,2.969779,1.900526,ASC
176,E01000181,Barnet029D,E09000003,Barnet,1519,1711,177500,732500,1216,659,...,30680,45890,0.153313,3.719620,868.0,251.0,617.0,1.369472,3.566307,ASC
186,E01000191,Barnet014F,E09000003,Barnet,1370,1525,184000,495000,982,317,...,30260,42710,-0.221884,2.096955,1250.0,740.0,510.0,1.131978,2.318838,ASC
194,E01000199,Barnet025B,E09000003,Barnet,1491,1617,196250,765000,1080,467,...,32850,45740,0.212867,3.733138,823.0,247.0,576.0,1.278470,3.520271,ASC
196,E01000201,Barnet028C,E09000003,Barnet,1462,1531,295000,1042500,1043,415,...,34940,51120,0.593226,5.170031,574.0,107.0,467.0,1.036537,4.576805,ASC
202,E01000207,Barnet033C,E09000003,Barnet,1514,1583,600000,1205000,1078,575,...,38090,55210,2.674753,6.413874,27.0,59.0,-32.0,-0.071026,3.739121,ASC
207,E01000212,Barnet035D,E09000003,Barnet,1344,1428,307500,1067500,1003,582,...,38310,52340,1.274575,5.688677,232.0,83.0,149.0,0.330715,4.414103,ASC
208,E01000213,Barnet033F,E09000003,Barnet,1405,1438,1030000,2203500,907,431,...,49520,68560,5.090985,11.874852,4.0,5.0,-1.0,-0.002220,6.783867,ASC
212,E01000217,Barnet035F,E09000003,Barnet,1509,1725,200000,760000,984,437,...,33640,45590,0.163525,3.299910,861.0,337.0,524.0,1.163052,3.136384,ASC
223,E01000228,Barnet007A,E09000003,Barnet,1367,1481,177475,886500,944,263,...,29650,44630,-0.541356,3.830754,1666.0,225.0,1441.0,3.198394,4.372110,ASC
244,E01000249,Barnet001B,E09000003,Barnet,1515,1525,173250,490000,1091,405,...,31270,46630,-0.288919,2.264171,1320.0,659.0,661.0,1.467133,2.553091,ASC
262,E01000267,Barnet005A,E09000003,Barnet,1495,1520,121500,367500,1090,357,...,30240,42080,-0.599314,1.284924,1767.0,1280.0,487.0,1.080928,1.884239,ASC
264,E01000269,Barnet005C,E09000003,Barnet,1334,1425,162225,392000,964,245,...,29510,41030,-0.701780,1.172752,1929.0,1366.0,563.0,1.249615,1.874533,ASC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4762,E01033575,Newham034G,E09000025,Newham,304,1021,182500,340000,191,25,...,19750,40930,-1.488523,1.968210,3731.0,805.0,2926.0,6.494448,3.456733,ASC
4763,E01033576,Newham034H,E09000025,Newham,386,1295,95475,250000,243,31,...,19460,36620,-1.910139,0.623531,4641.0,1921.0,2720.0,6.037218,2.533670,ASC
4765,E01033578,Newham013E,E09000025,Newham,527,1273,121500,222000,364,78,...,20380,36130,-1.500924,0.407653,3764.0,2195.0,1569.0,3.482498,1.908577,ASC
4766,E01033579,Newham013F,E09000025,Newham,537,1293,90000,214000,371,80,...,23420,38340,-1.524794,0.694540,3825.0,1853.0,1972.0,4.376983,2.219334,ASC
4769,E01033582,Newham037H,E09000025,Newham,682,1381,130000,227500,502,129,...,28590,40760,-0.996781,0.868517,2476.0,1661.0,815.0,1.808946,1.865298,ASC
4770,E01033583,Newham013G,E09000025,Newham,1609,3081,106500,246950,1182,284,...,21860,35090,-1.567174,0.062014,3938.0,2731.0,1207.0,2.679015,1.629188,ASC
4772,E01033585,Newham034J,E09000025,Newham,1366,2445,80250,208000,938,194,...,19610,30750,-1.865038,-0.557774,4571.0,3918.0,653.0,1.449376,1.307263,ASC
4773,E01033586,Newham013H,E09000025,Newham,602,1410,67250,245000,416,89,...,21770,34580,-1.705080,0.040588,4267.0,2768.0,1499.0,3.327129,1.745668,ASC
4776,E01033589,Redbridge030H,E09000026,Redbridge,783,1676,89000,175000,558,142,...,22650,34780,-1.532448,0.530649,3846.0,2023.0,1823.0,4.046268,2.063097,ASC
4782,E01033595,Westminster013E,E09000033,Westminster,719,1175,320000,875000,585,244,...,32500,50240,0.603638,4.538194,568.0,140.0,428.0,0.949974,3.934556,ASC
4783,E01033596,Westminster013F,E09000033,Westminster,762,1235,241000,1139500,621,258,...,27800,46230,0.028999,5.324638,986.0,98.0,888.0,1.970974,5.295639,ASC
4784,E01033597,Westminster023F,E09000033,Westminster,558,990,79000,590000,420,104,...,23160,43470,-1.577707,2.575381,3960.0,540.0,3420.0,7.590914,4.153089,ASC
4786,E01033599,Westminster023G,E09000033,Westminster,892,1573,187500,685150,673,166,...,21420,34070,-1.122451,2.156060,2778.0,716.0,2062.0,4.576744,3.278511,ASC
4787,E01033600,Westminster007F,E09000033,Westminster,768,1224,250000,710000,648,376,...,34770,50620,1.036940,4.138478,343.0,188.0,155.0,0.344033,3.101538,ASC
4790,E01033603,Westminster009I,E09000033,Westminster,864,1333,165000,466750,697,264,...,24480,33350,-0.664969,1.383582,1880.0,1200.0,680.0,1.509304,2.048551,ASC
4797,E01033699,Hackney021G,E09000012,Hackney,668,1217,120000,314000,543,177,...,25080,38420,-1.092169,0.881951,2700.0,1643.0,1057.0,2.346081,1.974119,ASC
4798,E01033700,Hackney021H,E09000012,Hackney,829,1566,119500,302500,675,220,...,21210,39460,-1.247190,1.142829,3084.0,1404.0,1680.0,3.728870,2.390019,ASC
4802,E01033704,Hackney023F,E09000012,Hackney,799,1631,137500,267250,624,259,...,25370,41440,-0.700249,1.271282,1927.0,1291.0,636.0,1.411644,1.971531,ASC
4803,E01033705,Hackney028D,E09000012,Hackney,542,1417,83750,235000,400,109,...,21150,33380,-1.505367,-0.206201,3780.0,3211.0,569.0,1.262933,1.299166,ASC
4805,E01033707,Hackney021I,E09000012,Hackney,785,1303,180000,335000,589,168,...,22400,36060,-0.945893,0.744220,2372.0,1798.0,574.0,1.274031,1.690113,ASC
4814,E01033726,Greenwich034E,E09000011,Greenwich,1477,2493,109498,216000,1005,148,...,21240,33870,-1.752373,-0.544540,4366.0,3903.0,463.0,1.027659,1.207833,ASC
4818,E01033730,Greenwich035D,E09000011,Greenwich,748,1214,88700,330000,581,266,...,25150,41190,-0.660924,1.539995,1869.0,1087.0,782.0,1.735700,2.200919,ASC
4819,E01033731,Greenwich004E,E09000011,Greenwich,259,1017,107000,280000,186,32,...,22010,39020,-1.694458,1.047536,4246.0,1485.0,2761.0,6.128220,2.741993,ASC
4820,E01033732,Greenwich036D,E09000011,Greenwich,415,1053,143500,320000,330,134,...,28180,40700,-0.520787,1.565105,1628.0,1063.0,565.0,1.254054,2.085892,ASC
4821,E01033733,Greenwich036E,E09000011,Greenwich,451,1134,204900,386250,359,146,...,28920,45550,-0.189821,2.751397,1205.0,486.0,719.0,1.595868,2.941218,ASC
4822,E01033734,Greenwich004F,E09000011,Greenwich,344,1320,215000,273000,247,43,...,24010,38470,-1.092362,1.156505,2701.0,1396.0,1305.0,2.896533,2.248866,ASC
4823,E01033735,Greenwich004G,E09000011,Greenwich,270,1073,81500,146500,194,33,...,19150,32710,-1.941302,-0.362256,4673.0,3536.0,1137.0,2.523646,1.579046,ASC
4824,E01033736,Greenwich004H,E09000011,Greenwich,279,1125,163500,250000,201,35,...,23420,42640,-1.371718,1.567109,3418.0,1061.0,2357.0,5.231516,2.938827,ASC
4830,E01033742,Greenwich007F,E09000011,Greenwich,612,1352,78000,188000,427,86,...,22190,38020,-1.655118,0.334393,4158.0,2308.0,1850.0,4.106196,1.989510,ASC
4834,E01033746,Greenwich038E,E09000011,Greenwich,879,1464,200000,500000,682,313,...,29850,45220,0.063658,2.699337,964.0,495.0,469.0,1.040976,2.635680,ASC

In [7]:
# checkpoint - output file
# ascending_LSOA.to_csv("ascending_LSOA.csv")

In [8]:
# checkpoint - uncomment next line to start from this line onwards
# ascending_LSOA.to_csv("ascending_LSOA_basic.csv")


# extract the essential details of ascending LSOAs
ascending_LSOA = ascending_LSOA.drop(ascending_LSOA.columns[1:22],axis=1)

## Analysing Counts of LSOAs According to their Neighbourhoo States

In [9]:
# group lsoas according to their local authority

df_LA_counts = df_score.groupby(["Local_authority_name"]).size().reset_index()

In [10]:
# checking the number of lsoas that each local authority has respectively

df_LA_counts = pd.DataFrame(df_LA_counts)
df_LA_counts = df_LA_counts.rename(columns={0:"LSOA_count"})

In [11]:
df_LA_counts.head()

   Local_authority_name  LSOA_count
0  Barking and Dagenham         110
1                Barnet         211
2                Bexley         146
3                 Brent         173
4               Bromley         197

In [12]:
# now group lsoas by their local authority and then their neighbourhood states

df_LA_break = df_score.groupby(["Local_authority_name","status"]).size().reset_index()

In [13]:
# convert to dataframe and rename the data feature

df_LA_break = pd.DataFrame(df_LA_break)
df_LA_break = df_LA_break.rename(columns={0:"count"})

In [14]:
df_LA_break.head()

   Local_authority_name status  count
0  Barking and Dagenham    ASC      7
1  Barking and Dagenham    DEC      1
2  Barking and Dagenham    STB    102
3                Barnet    ASC     31
4                Barnet    DEC     37

In [15]:
# merge the 2 dataframes

df_LA_counts = df_LA_counts.merge(df_LA_break, left_on = "Local_authority_name", right_on = "Local_authority_name", how = "left")

In [16]:
df_LA_counts.head()

   Local_authority_name  LSOA_count status  count
0  Barking and Dagenham         110    ASC      7
1  Barking and Dagenham         110    DEC      1
2  Barking and Dagenham         110    STB    102
3                Barnet         211    ASC     31
4                Barnet         211    DEC     37

In [17]:
# compute the share of LSOA neighbourhood states in each local authority (in % terms)

df_LA_counts["count_share"] = df_LA_counts["count"] / df_LA_counts["LSOA_count"] * 100
df_LA_counts["count_share"] = df_LA_counts["count_share"].round(2)

In [18]:
df_LA_counts.head()

   Local_authority_name  LSOA_count status  count  count_share
0  Barking and Dagenham         110    ASC      7         6.36
1  Barking and Dagenham         110    DEC      1         0.91
2  Barking and Dagenham         110    STB    102        92.73
3                Barnet         211    ASC     31        14.69
4                Barnet         211    DEC     37        17.54

In [19]:
# extract info for only the ascending states

df_LA_counts_asc = df_LA_counts.loc[df_LA_counts["status"] == "ASC"]

In [20]:
# extract the 5 local authorities with the largest share of ascending lsoas

df_LA_counts_asc.nlargest(5, "count_share")

      Local_authority_name  LSOA_count status  count  count_share
55  Kensington and Chelsea         103    ASC     55        53.40
94             Westminster         128    ASC     46        35.94
70                  Newham         164    ASC     55        33.54
31                 Hackney         144    ASC     46        31.94
73               Redbridge         161    ASC     49        30.43

In [21]:
# extract info for only the descending states

df_LA_counts_dec = df_LA_counts.loc[df_LA_counts["status"] == "DEC"]

In [22]:
# extract the 5 local authorities with the largest share of descending lsoas

df_LA_counts_dec.nlargest(5, "count_share")

    Local_authority_name  LSOA_count status  count  count_share
23                Ealing         196    DEC     69        35.20
50              Hounslow         142    DEC     37        26.06
10                 Brent         173    DEC     45        26.01
20               Croydon         220    DEC     48        21.82
59  Kingston upon Thames          98    DEC     21        21.43